import Head from 'next/head'
import styles from '../../styles/Home.module.css'

const user = ({ userId, userName, userPhone, userSex }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>
          Server Side Render(SSR) 服务端渲染
        </h2>
        <h2>
          动态路由页面
        </h2>
        <h2>
          {`userId:${userId}`}
        </h2>
        <h2>
          {`userName:${userName}`}
        </h2>
        <h2>
          {`userPhone:${userPhone}`}
        </h2>
        <h2>
          {`userSex:${userSex}`}
        </h2>
        <h2>————Next.js学习————</h2>
      </main>
    </div>
  )
};

export const getServerSideProps = (ctx) => {
  const { params, req, res } = ctx
  console.log('res', res, 'req', req)
  const id = params.uid
  if (Number(id) > 10) {
    return { redirect: '/about' }
  }
  if (Number(id) > 5) {
    return { notFound: true }
  }
  return {
    props: {
      userId: id,
      userName: 'Mr.Zhu',
      userPhone: '138****6743',
      userSex: 'male'
    }
  }
}
export default user;
