import Head from 'next/head'
import styles from '../../styles/Home.module.css'

const user = ({ userName, userPhone, userSex }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>
          Server Side Render(SSR) 服务端渲染
        </h2>
        <h2>
          {`userName:${userName}`}
        </h2>
        <h2>
          {`userPhone:${userPhone}`}
        </h2>
        <h2>
          {`userSex:${userSex}`}
        </h2>
        <h2>————Next.js学习————</h2>
      </main>
    </div>
  )
};

export const getServerSideProps = () => {
  return {
    props: {
      userName: 'Mr.Zhu',
      userPhone: '138****6743',
      userSex: 'male'
    }
  }
}
export default user;
