import { useRouter } from "next/router";
import Head from 'next/head'
import styles from '../../styles/Home.module.css'

const page = ({ post }) => {
  const router = useRouter()
  console.log(router)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {
          post ?
            <>
              <h1 className={styles.title}>
                {post}
              </h1>
              <h3>{`路由：${router.query['id']}`}</h3>
            </>
            :
            <h1>{`正在努力为您加载中\`(*>﹏<*)′...`}</h1>
        }
        <h2>————Next.js学习————</h2>
      </main>
    </div>
  )
};

const posts = [
  { id: '1', value: 'id为1的外部数据' },
  { id: '2', value: 'id为2的外部数据' },
  { id: '3', value: 'id为3的外部数据' },
  { id: '4', value: 'id为4的外部数据' },
]

export const getStaticPaths = () => {
  // const paths = posts.map((post) => ({
  //   params: { id: post.id }
  // }))
  const paths = [{ params: { id: '1' } }, { params: { id: '2' } }]
  return { paths, fallback: true }
}

export const getStaticProps = ({ params }) => {
  const index = posts.findIndex(item => {
    return item.id === params.id
  })
  const post = posts[index]?.value
  if (!post)
    return { notFound: true }
  return { props: { post } }
}
export default page;