import Head from 'next/head'
import styles from '../../styles/Home.module.css'

const about = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>
          Static Site Generation(SSG) 静态生成
        </h2>
        <h1 className={styles.title}>{posts}</h1>
        <h2>————Next.js学习————</h2>
      </main>
    </div>
  )
};

export const getStaticProps = () => {
  console.log('getStaticProps again...')
  const posts = '这是一个外部数据'
  return {
    props: {
      posts
    },
    revalidate: 10
  }
}
export default about;
