import Head from 'next/head'
import styles from '../styles/Home.module.css'

const NotFoundPage = () => {
  return <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        哎呀！页面不见了/(ㄒoㄒ)/~~
      </h1>
      <h2>————Next.js学习————</h2>
    </main>
  </div>

};
export default NotFoundPage;